#!/usr/bin/env python3
"""Write src/parameters.lucb: every develop parameter's name, label, Properties
section, range, default and decimals, and the Parameter enum Base code reads
them by. Edit the list here, then run tools/parameters.py."""
from pathlib import Path
# (name, label, section, low, high, default, decimals)
P=[]
def add(n,l,s,lo,hi,d=0.0,dec=0): P.append((n,l,s,lo,hi,d,dec))
add("temperature","Temperature","White Balance",0,50000,0,0)
add("tint","Tint","White Balance",-150,150)
add("exposure","Exposure","Exposure & Tone",-6,6,0,2)
for n in ["contrast","highlights","shadows","whites","blacks"]: add(n,n.capitalize(),"Exposure & Tone",-100,100)
add("levels_black","Input Black","Levels",0,1,0,3)
add("levels_white","Input White","Levels",0,1,1,3)
add("levels_gamma","Gamma","Levels",0.1,10,1,2)
add("levels_out_black","Output Black","Levels",0,1,0,3)
add("levels_out_white","Output White","Levels",0,1,1,3)
add("vibrance","Vibrance","Color",-100,100)
add("saturation","Saturation","Color",-100,100)
bands=["red","orange","yellow","green","aqua","blue","purple","magenta"]
for b in bands:
    add(b+"_hue",b.capitalize()+" Hue","Color Mixer",-100,100)
    add(b+"_saturation",b.capitalize()+" Saturation","Color Mixer",-100,100)
    add(b+"_luminance",b.capitalize()+" Luminance","Color Mixer",-100,100)
for r in ["shadows","midtones","highlights","global"]:
    add("grade_"+r+"_hue",r.capitalize()+" Hue","Color Grading",0,360,0,0)
    add("grade_"+r+"_saturation",r.capitalize()+" Saturation","Color Grading",0,100)
    add("grade_"+r+"_luminance",r.capitalize()+" Luminance","Color Grading",-100,100)
add("grade_balance","Balance","Color Grading",-100,100)
add("grade_blending","Blending","Color Grading",0,100,50)
add("bw","Black & White","Black & White",0,1)
defaults={"red":40,"orange":30,"yellow":20,"green":-10,"aqua":-20,"blue":-30,"purple":-10,"magenta":20}
for b in bands: add("bw_"+b,b.capitalize(),"Black & White",-200,300,defaults[b])
add("bw_tint_hue","Tint Hue","Black & White",0,360)
add("bw_tint_amount","Tint Amount","Black & White",0,100)
add("lens_vignetting","Vignetting","Lens",0,100)
add("lens_midpoint","Midpoint","Lens",0,100,50)
add("vignette_amount","Amount","Effects",-100,100)
add("vignette_midpoint","Midpoint","Effects",0,100,50)
add("vignette_roundness","Roundness","Effects",-100,100)
add("vignette_feather","Feather","Effects",0,100,50)
add("grain_amount","Grain","Effects",0,100)
add("grain_size","Grain Size","Effects",0,100,25)
add("grain_roughness","Roughness","Effects",0,100,50)
add("view","View","View",0,2,0,0)
enum="\n".join(f"    {p[0]} = {i}" for i,p in enumerate(P))
def num(v): return repr(float(v))
table=",\n".join(f'    ParameterSpec("{p[0]}", "{p[1]}", "{p[2]}", {num(p[3])}, {num(p[4])}, {num(p[5])}, {p[6]})' for p in P)
(Path(__file__).resolve().parents[1] / "src/parameters.lucb").write_text(f"""## Generated by tools/parameters.py; do not edit. Every develop parameter, its
## name in the text form, its label and Properties section, range, default and
## decimals. settings.lucb says what each does.

## One parameter's description.
pub struct ParameterSpec:
    pub let name: str
    pub let label: str
    pub let section: str
    pub let low: f64
    pub let high: f64
    pub let default: f64
    pub let decimals: i64

## Every develop parameter, in text-form order.
pub enum Parameter as u8:
{enum}

## How many parameters there are.
pub let parameter_count: usize = {len(P)}

pub let parameters: ParameterSpec[{len(P)}] = [
{table}]
""")

